### ISSUE TITLE
undefined method `add_template_helper' for SwaggerUiEngine::SwaggerDocsController:Class

### ISSUE THREAD

**Issue by scottbarrow** [zuzannast/swagger_ui_engine#23]
rails 5.1.5 
api-mode

installed gem as per instructions, this error is displayed on visiting /api_docs
```
module SwaggerUiEngine
  class SwaggerDocsController < ApplicationController
    include SwaggerUiEngine::ConfigParser
    include SwaggerUiEngine::OauthConfigParser
    add_template_helper SwaggerUiEngine::TranslationHelper
    layout 'swagger_ui_engine/layouts/swagger', except: %w(oauth2)
    before_action :set_configs, :set_oauth_configs
    def oauth2```

**Comment by zuzannast** [comment]
Hey @scottbarrow could you give me some more information on your application application config? I'll send an example API-only application for you to compare.

**Comment by zuzannast** [comment]
@scottbarrow any update on that? If not or if the problem is solved, I'll close that issue.

**Comment by scottbarrow** [comment]
sorry not had chance to try yet, but please feel free to close the issue

**Comment by denys281** [comment]
@zuzannast  Have same issue. For now couldn't find what's wrong)

**Comment by denys281** [comment]
@misa-itk 

The problem is, that you need load additional libraries, since rails "api" version doesn't load them by default. I don't know how example that  @zuzannast  posted above works)

For me works next: 

In your application controller add:

```
  include AbstractController::Helpers
  include ActionView::Layouts
  include ActionController::RequestForgeryProtection
```

And it should works.
