### ISSUE TITLE
Documentation doesn't match gemspec

### ISSUE THREAD

**Issue by ekampp** [zuzannast/swagger_ui_engine#28]
Hey there. 

Documentation states Rails `>= 4.2`, but gemfile states `~> 4.2`

<img width="363" alt="screen shot 2018-07-12 at 07 13 30" src="https://user-images.githubusercontent.com/40206/42613817-2eefa25e-85a3-11e8-9d8c-90faccee3fa2.png">

When installing, bundler says this:

```
Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    rails (~> 5.2.0)

    swagger_ui_engine was resolved to 1.1.1, which depends on
      rails (~> 4.2)
```

**Comment by zuzannast** [comment]
True, it's a bug introduced in the latest release. I'll release a fixed version in #24, thank you!
