### ISSUE TITLE
Basic auth support

### ISSUE THREAD

**Issue by pedelman** [ZuzannaSt/swagger_ui_engine#7]
It would be cool to support locking down access to the swagger doc using basic auth. This functionality is supported in other swagger ui gems as well as projects like resque web.

Here is an example implementation from another swagger gem. 

https://github.com/batdevis/swagger_engine/blob/master/app/controllers/swagger_engine/application_controller.rb

Then we can configure the credentials inside an initializer as well.

```rb
# from https://github.com/batdevis/swagger_engine#basic-http-auth
SwaggerEngine.configure do |config|
  config.admin_username = ENV['ADMIN_USERNAME']
  config.admin_password = ENV['ADMIN_PASSWORD']
end
```

Thanks for putting this together!

**Comment by ZuzannaSt** [comment]
Thanks @pedelman, I'll include this in the next version 👍
