### ISSUE TITLE
Issue getting basic auth to work

### ISSUE THREAD

**Issue by pedelman** [ZuzannaSt/swagger_ui_engine#8]
Hello. I saw that Basic Auth was added to the gem! Awesome!

I was playing around and was running into some issues getting the basic auth functionality to work in dev. Maybe we can add the basic auth to the example rails app as a proof of functionality.

When I go into the Rails console, I can see:

```rb
irb(main):003:0> SwaggerUiEngine.configuration
=> #<SwaggerUiEngine::Configuration:0x005569cd6ea668 @admin_username="admin", @admin_password="admin", @swagger_url={:v1=>"/api/v1/swagger.yaml"}, @doc_expansion="list", @model_rendering="schema", @request_headers=true, @json_editor=true>
```

I can see that the `admin_username` and `admin_password` are set, but no prompt in the bowser. Anything I am missing?

Thanks again!!

**Comment by ZuzannaSt** [comment]
Hello @pedelman, thanks again for reaching out. I've added a HTTP basic auth to the example app, so you can go through the [README](https://github.com/ZuzannaSt/swagger_ui_engine_example) and test it live on [Heroku](https://swagger-ui-engine-example.herokuapp.com/). 

It may be a silly question but did you remember to restart your application after changing the config file? :)
